DOWNSTREAM_REPOS = ["astropy", "scipy", "numpy", "pandas", "gammapy", "ccdproc", "dask", "h5py", "joblib",
                    "networkx", "nilearn", "numexpr", "obspy", "specutils", "statsmodels", "seaborn", "sympy",
                    "theano", "xarray", "photutils", "asdf", "pyregion", "brian2", "naima", "pyamg", "astroplan",
                    "numba", "mahotas", "randomgen", "sparse", "alphalens", "pyjet", "numbagg", "cvxpy", "aplpy",
                    "deap", "mpmath", "oct2py", "atpy", "gwcs", "pymc3", "starfish", "verde", "astroimtools",
                    "stginga", "pydl", "iexfinance", "plydata", "ibis", "matplotlib", "sklearn", "skbio",
                    "tables", "astropy_helpers", "patsy" , "radio_beam", "shared_ndarray", "nrrd", "synphot",
                    "nptdms", "bottleneck", "poppy", "feets", "pvmismatch", "utide", "npstreams", "pyxrd",
                    "spampy", "pyrr", "hienoi", "molml", "oommftools", "nnlib", "kravatte", "geometer", "slugnet",
                    "zappy", "gfmm", "pdepy", "tidynamics", "texpy", "psopy", "randnla", "indi", "pytablewriter",
                    "prince", "coinsta", "kodiak", "phildb", "espandas", "validada", "partridge", "finta", "pyik",
                    "dicom_numpy", "json_tricks", "numpy_buffer", "datacompy", "deepgraph", "lens"]
